import type { Metadata } from "next";
import Link from 'next/link'
import type { RootLayoutProps } from "../app/types"
import { Albert_Sans, Montserrat_Alternates } from "next/font/google";
import PFLogoIcon from "../../public/printforge-logo-icon.svg"
import PFLogo from "../../public/printforgelogo.svg"
import Image from 'next/image'
import "./globals.css";

const albertSans = Albert_Sans({
  subsets: ["latin"],
  display: "swap"
})

const montserratAlternates = Montserrat_Alternates({
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-montserrat-alternates"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}:RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`${albertSans.className} ${montserratAlternates.variable}`}
      >
        <header className="w-full bg-white">
          <nav className="flex justify-between px-6 py-4">
            <Link href="/">
            <div className="relative flex">
              {/* Desktop logo */}
              <Image
                src={PFLogo.src}
                alt="PrintForge Logo"
                className="w-[200px] h-auto hidden md:block"
                width={120}
                height={120}
              />
              {/* Mobile logo */}
              <Image
                src={PFLogoIcon.src}
                alt="PrintForge Logo icon"
                className="w-[40px] h-auto block md:hidden"
                width={48}
                height={48}
              />
            </div>
            </Link>
            <ul className="flex items-center gap-2.5">
              <li className="text-sm uppercase cursor-pointer">
                <Link href="/3d-models">3D Models</Link>
              </li>
              <li className="text-sm uppercase cursor-pointer">
                <Link href="/about">About</Link>
              </li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
